jwt:
  secret-ket: 17

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${ZZEKAK_API_DB_URL}?characterEncoding=UTF-8&serverTimezone=KST
    username: ${ZZEKAK_API_DB_USER_NAME}
    password: ${ZZEKAK_API_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  charset:
    console: UTF-8
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace